style:
  ForbiddenComment:
    active: false
  WildcardImport:
    active: false
  MagicNumber:
    active: true
    excludes:
      - '**/*Test.kt'
naming:
  FunctionNaming:
    excludeClassPattern: '.*Test'
