name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - run: brew install libpq
      - run: gradle wrapper --no-daemon
      - run: ./gradlew build detekt --no-daemon -Ptargets=macosArm64
