name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - run: brew install libpq
      - run: gradle wrapper --no-daemon
      - run: ./gradlew build detekt --no-daemon -Ptargets=linuxX64
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - run: brew install libpq
      - run: gradle wrapper --no-daemon
      - run: ./gradlew build -x check --no-daemon -Ptargets=macosArm64
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
  release:
    runs-on: macos-14
    # Disabled for now.
    if: false
    needs:
      - test
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - run: brew install libpq
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
      - run: gradle wrapper --no-daemon
      - run: ./gradlew publishAllPublicationsToSonatypeRepository -x check --no-daemon